import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';

/// Camera rest frames, one per score page, read from the `pageN` markers of
/// `a/score.json` inside a dotLottie package generated by verovio_lottie.
///
/// The whole-score composition lays every page side by side on a horizontal
/// track and a camera layer frames one page at a time; each `pageN` marker
/// (`{"cm":"pageN","tm":<frame>,"dr":1}`) pins the frame where the camera
/// rests on page N. Seeking the player to one of these frames shows that
/// page — no state machine needed for plain page navigation (see C04:
/// `sm_page` only offers sequential peek/cover events and expects two
/// cooperating `Player` instances, which the Flutter plugin cannot host).
Future<List<int>> pageRestFrames(String dotLottiePath) async {
  final bytes = await File(dotLottiePath).readAsBytes();
  final archive = ZipDecoder().decodeBytes(bytes);
  final score = archive.files.where((f) => f.name == 'a/score.json');
  if (score.isEmpty) return const [0];
  final doc = jsonDecode(utf8.decode(score.first.content as List<int>))
      as Map<String, dynamic>;
  final markers = (doc['markers'] as List?) ?? const [];
  final rests = <int, int>{}; // page index -> rest frame
  final pageMarker = RegExp(r'^page(\d+)$');
  for (final marker in markers) {
    final m = (marker as Map).cast<String, dynamic>();
    final match = pageMarker.firstMatch('${m['cm']}');
    if (match == null) continue;
    final frame = m['tm'];
    if (frame is num) rests[int.parse(match.group(1)!)] = frame.toInt();
  }
  if (rests.isEmpty) return const [0]; // single-page packages have no markers
  final ordered = rests.keys.toList()..sort();
  return [for (final k in ordered) rests[k]!];
}
